M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date Mon 22 Jan 2024 11:32:44 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-22T23:32:44-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.037Y-1.787
X4.237Y-3.837
X5.337Y-3.837
X5.937Y-1.837
M30
